"""Curated source-tier table pins.

The table is generated by scripts/refresh_source_lists.py from IFCN + Wikipedia
RSP + an editorial supplement and loaded by agent.factcheck.sources. These tests
pin the *load-time precedence and override semantics* — the places where a
future upstream refresh could silently re-tier a domain into the wrong bucket
and change verdicts. They assert against the committed JSON artifact (no
network).
"""
from __future__ import annotations

import pytest

from agent.factcheck import sources
from agent.factcheck.sources import (
    build_quality_table,
    is_non_evidence_domain,
    source_lists_version,
)


def _tier(domain: str):
    return sources._TIER_BY_DOMAIN.get(domain)


# ── Preprints: RSP "deprecated" must NOT demote them to low-quality ──────────
# RSP deprecates preprint servers for Wikipedia *citation*; as fact-check
# *evidence* they are primary sources. The editorial primary-source override
# must win over the RSP low-quality listing, or cited science lands in the same
# do-not-count bucket as misinformation.
@pytest.mark.parametrize("domain", ["arxiv.org", "biorxiv.org", "medrxiv.org"])
def test_preprints_are_primary_source_not_low_quality(domain):
    tier, tier_source, _ = _tier(domain)
    assert tier == "primary-source", f"{domain} regressed to {tier!r}"
    assert tier_source == "editorial-curated"


# Magazines RSP rates reliable must stay reputable-news, NOT get swept into the
# primary-source override alongside the preprints.
@pytest.mark.parametrize("domain", ["nationalgeographic.com", "scientificamerican.com"])
def test_reliable_magazines_stay_reputable_news(domain):
    tier, tier_source, _ = _tier(domain)
    assert tier == "reputable-news"
    assert tier_source == "wikipedia-rsp"


# ── Satire: RSP "generally unreliable" must NOT route satire to low-quality ──
def test_satire_overrides_rsp_low_quality():
    tier, tier_source, _ = _tier("theonion.com")
    assert tier == "satirical"
    assert tier_source == "editorial-curated"


# ── IFCN precedence: a fact-checker also listed by RSP stays fact-checker ────
@pytest.mark.parametrize("domain", ["snopes.com", "politifact.com", "africacheck.org"])
def test_current_ifcn_signatories_are_fact_checker_via_ifcn(domain):
    tier, tier_source, _ = _tier(domain)
    assert tier == "fact-checker"
    assert tier_source == "ifcn"


# ── Coverage-preserving decision: established fact-checkers whose IFCN
# verification has lapsed stay fact-checker via the editorial supplement, NOT
# dropped to the nondeterministic model-prior path. tier_source must disclose
# that this is our editorial judgement, not a current IFCN claim.
@pytest.mark.parametrize(
    "domain",
    ["fullfact.org", "altnews.in", "correctiv.org", "maldita.es", "leadstories.com"],
)
def test_lapsed_signatories_are_fact_checker_via_editorial(domain):
    hit = _tier(domain)
    assert hit is not None, f"{domain} dropped from curated table"
    tier, tier_source, _ = hit
    assert tier == "fact-checker"
    assert tier_source == "editorial-curated"


# ── RSP-sourced tiers ───────────────────────────────────────────────────────
def test_rsp_reputable_and_low_quality():
    assert _tier("nytimes.com")[:2] == ("reputable-news", "wikipedia-rsp")
    assert _tier("dailymail.co.uk")[:2] == ("low-quality", "wikipedia-rsp")
    assert _tier("infowars.com")[:2] == ("low-quality", "wikipedia-rsp")


def test_rsp_never_classifies_a_domain_both_ways():
    import json

    raw = json.loads(sources._DATA_PATH.read_text())
    dom = raw["sources"]["wikipedia_rsp"]["domains"]
    assert not (set(dom["reputable-news"]) & set(dom["low-quality"]))


# ── End-to-end subdomain fallback (via the production batch entrypoint) ──────
def test_subdomain_fallback():
    e = build_quality_table(["https://www.snopes.com/fact-check/x"])[0]
    assert e.tier == "fact-checker" and e.tier_source == "ifcn"
    e = build_quality_table(["http://sub.who.int/page"])[0]
    assert e.tier == "primary-source"


# ── Non-evidence exclusion ───────────────────────────────────────────────────
@pytest.mark.parametrize("url", [
    "https://www.pinterest.com/pin/123",
    "https://gettyimages.com/photo/x",
    "https://images.gettyimages.com/a.jpg",   # subdomain fallback
    "https://www.shutterstock.com/image",
    "https://aws.amazon.com/docs",            # subdomain fallback → amazon.com
    "https://quora.com/q/abc",
])
def test_non_evidence_domains_are_flagged(url):
    assert is_non_evidence_domain(url) is True


@pytest.mark.parametrize("url", [
    "https://nytimes.com/article",
    "https://youtube.com/watch?v=1",   # social/video deliberately NOT excluded
    "https://snopes.com/fact-check/x",
    "https://who.int/news",
])
def test_real_sources_not_flagged(url):
    assert is_non_evidence_domain(url) is False


def test_build_quality_table_drops_non_evidence():
    rows = build_quality_table([
        "https://nytimes.com/a",
        "https://www.pinterest.com/pin/9",
        "https://gettyimages.com/p",
        "https://snopes.com/x",
    ])
    urls = {r.url for r in rows}
    assert not any("pinterest" in u or "gettyimages" in u for u in urls)
    assert len(rows) == 2  # nytimes + snopes only


# ── Reproducibility metadata is populated from the artifact ──────────────────
def test_version_fingerprint_is_pinnable():
    v = source_lists_version()
    assert v["ifcn_commit"], "IFCN commit sha not captured"
    assert v["wikipedia_rsp_revids"], "RSP revids not captured"
    assert v["lists_generated_at"]
