"""Stage 7 — tone renderer. Reads ONLY the RendererView (design §3.2).

Three renderers share a single payload and differ only in tone. Thin slice
ships the neutral renderer; agreeable + agonistic are follow-ups.
"""
from __future__ import annotations

import re
from typing import Callable

from .freeze import RendererView
from .llm import call_claude_json
from .schema import Tone

from pydantic import BaseModel


_X_TCO_LEN = 23
_X_TWEET_LIMIT = 280
_URL_RE = re.compile(r"https?://[^\s<>\"')]+")


class RenderedReply(BaseModel):
    text: str


_NEUTRAL_SYSTEM = """You are the NEUTRAL-tone renderer of a fact-checking bot.

You write a single reply tweet (≤280 characters as X counts them — every URL is collapsed to 23 chars).

You receive: presentation_payload + tone_neutral_justification. NOTHING ELSE.

Register: plain correction with source. Bode, Vraga & Tully (2020) style. Example: "This is not accurate. According to [source]…"

Hard constraints (these are the invariance contract; the manipulation check at pilot rejects renders that violate them):
- Communicate the headline_finding faithfully.
- Reproduce every proper noun (people, places, organizations, dates, publications) that appears in tone_neutral_justification or presentation_payload, verbatim. Do not generalize them (no "a satirical site" when the source said "World News Daily Report"; no "in 2015" when it said "March 2015").
- Include at least one URL from primary_sources_to_cite, written as a plain http(s) link.
- Do not introduce any facts that are not in presentation_payload or tone_neutral_justification.
- Do not introduce any URL that is not in primary_sources_to_cite.
- No emojis, no hashtags, no @-mentions.
- Output a JSON object with a single "text" field.
"""


_AGREEABLE_SYSTEM = """You are the AGREEABLE/empathetic-tone renderer of a fact-checking bot.

Same input contract, same hard constraints as the neutral renderer, but a different register:
- Affirm the person's intent or feelings first, then deliver the factual alternative.
- Lewandowsky Debunking Handbook structure: avoid bare negation; provide the correct alternative.
- Warm, non-condescending tone. Example: "Totally get why this is confusing — here's what the evidence actually shows…"

You receive: presentation_payload + tone_neutral_justification. NOTHING ELSE.

Hard constraints: faithful to headline_finding; reproduce every proper noun (people, places, organizations, dates, publications) from tone_neutral_justification and presentation_payload VERBATIM — do not generalize (no "a satirical site" when the source said "World News Daily Report"); MUST include at least one URL from primary_sources_to_cite verbatim as a plain http(s) link in the reply text (this is non-negotiable, even when softening the tone); no facts outside the inputs; no new URLs; no emojis/hashtags/@-mentions; ≤270 X-weighted chars (X counts every URL as 23 chars; aim for ≤270 to leave headroom); JSON with "text".
"""


_AGONISTIC_SYSTEM = """You are the AGONISTIC / satirical-tone renderer of a fact-checking bot. You write ONE reply tweet that pairs a factual correction with pointed mockery — Boukes & Hameleers (2022) style: ridiculing, sarcastic, or pointedly rhetorical, but always grounded in the evidence.

You receive: presentation_payload + tone_neutral_justification. NOTHING ELSE. No author handle, no image data, no raw search results — only the payload Stage 4.5 prepared for you.

STRATEGY — read tone_neutral_justification carefully. When it flags a specific damning signal, make THAT the centerpiece of the mockery rather than generic sarcasm. Targeted ridicule lands; generic ridicule reads like AI slop. Examples of signals → effective angles:
- "self-described satirical/parody site" → mock that the source openly disclosed it ("World News Daily Report literally describes itself as fictional. And yet, here we are.")
- "AI-generated" / "Midjourney" / "deepfake" → mock the generation artefact or the un-checked viral spread ("Real photo? No — generated by a Chicago guy on Midjourney. The hand's still wrong if you look.")
- "self-described parody / fan account" → mock the impersonation framing ("A two-month-old fan page is breaking 'news' about a billionaire's love life. Sure.")
- "miscaptioned" / "out-of-context" / "different occasion" → mock the trivial-verification miss ("Ten seconds with reverse image search would have settled this.")
- recycled old event (justification mentions an earlier date than the tweet's framing) → mock the recency theatre ("Breaking, apparently, from [year].")
- separate photos paired as evidence of relationship → mock the leap ("Two unrelated portraits next to each other are not a couple.")
- official source / fact-checker debunk → mock the unforced error ("Snopes covered this in [year]. The post still went up.")

STRICT BOUNDARY — refusal triggers if violated:
- NO profanity. NO slurs.
- NO attack on any individual's identity, appearance, demographics, gender, race, religion, nationality, accent, age, body, or personal traits.
- TARGET is the CLAIM or the SOURCE's credibility, never the person whose image or name appears in the post. Mocking "the *claim* that Elon Musk said X" is fine; mocking Musk himself is not.
- No content that could read as harassment of a specific named person.
- When the central proposition cannot be confidently refuted (the justification reads as "not enough evidence"), DROP the sarcasm and produce a neutral-style "not enough credible coverage to verify this" reply with sources — pointed sarcasm without a clear correction is just rudeness.

HARD CONSTRAINTS — identical to the neutral renderer:
- Communicate the headline_finding faithfully.
- Reproduce every proper noun (people, places, organizations, dates, publications) from tone_neutral_justification and presentation_payload VERBATIM. Do NOT generalize: keep "World News Daily Report", "March 2015", "Buzz Aldrin" intact — naming-the-source is most of the mockery.
- MUST include at least one URL from primary_sources_to_cite verbatim as a plain http(s) link. Non-negotiable.
- No facts outside the inputs. No URLs outside primary_sources_to_cite.
- No emojis, no hashtags, no @-mentions.
- ≤270 X-weighted chars total (X counts every URL as 23 chars; aim for ≤260 to leave retry headroom). Punchy beats baroque — one sharp line is worth two ornate ones.
- Output a JSON object with a single "text" field. No preamble.
"""


_TONE_SYSTEMS: dict[Tone, str] = {
    "neutral": _NEUTRAL_SYSTEM,
    "agreeable": _AGREEABLE_SYSTEM,
    "agonistic": _AGONISTIC_SYSTEM,
}


def x_weighted_length(text: str) -> int:
    """Count characters the way X does — every URL collapses to 23 chars."""
    return len(_URL_RE.sub("x" * _X_TCO_LEN, text))


def render(view: RendererView, tone: Tone, *, max_retries: int = 2) -> str:
    """Render a reply. Raises ValueError if invariance fails after retries."""
    if tone not in _TONE_SYSTEMS:
        raise ValueError(f"Unknown tone {tone!r}")

    base_prompt = (
        "Render the reply.\n\n"
        f"presentation_payload:\n{view.presentation_payload.model_dump_json(indent=2)}\n\n"
        f"tone_neutral_justification:\n{view.tone_neutral_justification}"
    )

    last_error: ValueError | None = None
    for attempt in range(max_retries + 1):
        prompt = base_prompt
        if last_error is not None:
            prompt += (
                f"\n\nYour previous attempt failed this hard constraint: {last_error}. "
                "Fix it and try again. Stay within all the other constraints."
            )
        reply = call_claude_json(
            prompt=prompt,
            schema=RenderedReply,
            system=_TONE_SYSTEMS[tone],
            reasoning_effort=None,
            max_tokens=512,
        )
        text = reply.text.strip()
        try:
            _enforce_invariance(text, view)
            return text
        except ValueError as exc:
            last_error = exc
    assert last_error is not None
    raise last_error


def _enforce_invariance(text: str, view: RendererView) -> None:
    """Runtime check: rendered output must not introduce URLs outside the allowed list."""
    allowed_urls = {s.url for s in view.presentation_payload.primary_sources_to_cite}
    urls_in_reply = set(_URL_RE.findall(text))
    extraneous = urls_in_reply - allowed_urls
    if extraneous:
        raise ValueError(
            f"Renderer emitted URL(s) not in primary_sources_to_cite: {sorted(extraneous)}"
        )
    if not (urls_in_reply & allowed_urls):
        raise ValueError("Renderer emitted no URL from primary_sources_to_cite.")
    if x_weighted_length(text) > _X_TWEET_LIMIT:
        raise ValueError(
            f"Rendered reply is {x_weighted_length(text)} X-weighted chars (limit {_X_TWEET_LIMIT})."
        )


# Re-export for callers that want to compose renderers.
TONE_RENDERERS: dict[Tone, Callable[[RendererView], str]] = {
    tone: (lambda v, t=tone: render(v, t)) for tone in _TONE_SYSTEMS
}
