"""Source-reliability lookup (design §4.5.2).

Two phases per URL:
  1. Curated table, loaded from data/source_lists.json (generated by
     scripts/refresh_source_lists.py from authoritative public lists:
     IFCN verified signatories + Wikipedia RSP, plus a hand-curated editorial
     supplement for tiers with no public feed). Lookup does subdomain → parent
     fallback. Each hit's `tier_source` records which list it came from
     (ifcn / wikipedia-rsp / editorial-curated), so a verdict can be traced to
     its backing — the design's separate IFCN / Wikipedia / MBFC steps collapse
     to a single precedence-ordered lookup here.
  2. Claude model-prior classifier for everything else, batched per
     pipeline invocation and cached for the process lifetime.

Failure to classify falls through to `unknown`.

To refresh the lists from upstream: `python -m scripts.refresh_source_lists`.
"""
from __future__ import annotations

import json
import logging
import threading
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

import anthropic

from agent.shared.text import canonicalize_url

from .schema import SourceQualityEntry, SourceTier, TierSource


logger = logging.getLogger(__name__)


# ── Curated tier table (loaded from data/source_lists.json) ─────────────────
#
# The curated table is generated by scripts/refresh_source_lists.py from
# authoritative public lists and committed as data/source_lists.json:
#   • ifcn          — IFCN verified signatories (the network's own list).
#   • wikipedia_rsp — Wikipedia:Reliable sources/Perennial sources, status
#                     codes mapped to tiers (gr → reputable-news; gu/d/b →
#                     low-quality; no-consensus/marginal left unclassified).
#   • editorial     — hand-curated supplement for tiers with no public feed
#                     (primary-source, satirical) + gap-fillers.
# Precedence ifcn > wikipedia_rsp > editorial: the first list to claim a
# domain wins, so an IFCN fact-checker is never demoted by an RSP news listing
# and the editorial block only fills domains the external lists don't cover.
# Each entry's tier_source records which list it came from, for the verdict's
# reproducibility metadata (design §5.1 source_reliability_lists_version).

_DATA_PATH = Path(__file__).resolve().parent / "data" / "source_lists.json"


def _load_curated_table() -> tuple[
    dict[str, tuple[SourceTier, TierSource, str]], set[str], dict
]:
    """Build {domain → (tier, tier_source, rationale)} from the JSON artifact,
    applying precedence, plus the non-evidence exclusion set. Returns
    (table, non_evidence_domains, provenance). First writer per domain wins."""
    raw = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
    src = raw["sources"]
    table: dict[str, tuple[SourceTier, TierSource, str]] = {}
    non_evidence: set[str] = set(src.get("non_evidence", {}).get("domains", []))

    def _add(domain: str, tier: SourceTier, tier_source: TierSource, rationale: str):
        if domain and domain not in table:
            table[domain] = (tier, tier_source, rationale)

    ed = src["editorial"]

    def _add_editorial(tier: SourceTier):
        rationale = f"Editorial supplement ({tier}); no public list covers this domain."
        for d in ed["domains"].get(tier, []):
            _add(d, tier, ed["tier_source"], rationale)

    # 1. IFCN — fact-checkers (most authoritative signal for a fact-checker).
    ifcn = src["ifcn"]
    for d in ifcn["domains"]:
        _add(d, ifcn["tier"], ifcn["tier_source"], ifcn["rationale"])

    # 2. Editorial "satirical" + "primary-source" — applied BEFORE RSP on
    #    purpose, because RSP's reliability axis answers a different question
    #    than our tier:
    #      • Satire (The Onion) is RSP "generally unreliable" — correct for
    #        *citation*, but we route satire down a distinct satirical
    #        action/tone path, not the misinformation path.
    #      • Preprint servers (arxiv/biorxiv/medrxiv) are RSP "deprecated" —
    #        i.e. don't cite as settled fact on Wikipedia — but as *evidence*
    #        in a fact-check they are primary sources, not low-quality
    #        misinformation. Without this override a cited preprint lands in
    #        the same do-not-count bucket as infowars.
    #    These are the more specific classifications, so they win over RSP.
    _OVERRIDE_TIERS = ("satirical", "primary-source")
    for tier in _OVERRIDE_TIERS:
        _add_editorial(tier)

    # 3. Wikipedia RSP — reputable-news / low-quality.
    rsp = src["wikipedia_rsp"]
    for tier, domains in rsp["domains"].items():
        rationale = rsp["rationales"][tier]
        for d in domains:
            _add(d, tier, rsp["tier_source"], rationale)

    # 4. Remaining editorial tiers — fill gaps RSP/IFCN don't cover.
    for tier in ed["domains"]:
        if tier not in _OVERRIDE_TIERS:
            _add_editorial(tier)

    provenance = {name: block.get("provenance", {}) for name, block in src.items()}
    provenance["generated_at"] = raw.get("generated_at")
    return table, non_evidence, provenance


try:
    _TIER_BY_DOMAIN, _NON_EVIDENCE_DOMAINS, _SOURCE_LISTS_PROVENANCE = _load_curated_table()
except Exception:
    # The curated table is a packaged data file (data/source_lists.json). If it
    # is missing or unreadable, degrade gracefully rather than crashing every
    # fact-check at import time: an empty curated table means every domain
    # falls through to the model-prior classifier. Loud error so the gap is
    # obvious in logs / monitoring.
    logger.error(
        "Failed to load curated source lists from %s — running with an EMPTY "
        "curated table (all domains go to the model-prior classifier).",
        _DATA_PATH, exc_info=True,
    )
    _TIER_BY_DOMAIN = {}
    _NON_EVIDENCE_DOMAINS = set()
    _SOURCE_LISTS_PROVENANCE = {"error": "source_lists.json not loaded"}


def source_lists_provenance() -> dict:
    """Full provenance of the curated lists (URLs, commit, revids, notes)."""
    return _SOURCE_LISTS_PROVENANCE


def source_lists_version() -> dict:
    """Compact, pinnable identifiers for the curated lists — embedded in every
    frozen verdict's source_reliability_lists_version so a result can be tied
    to the exact upstream snapshot that produced its tiers (design §5.1)."""
    p = _SOURCE_LISTS_PROVENANCE
    return {
        "ifcn_commit": p.get("ifcn", {}).get("commit"),
        "wikipedia_rsp_revids": p.get("wikipedia_rsp", {}).get("subpage_revids"),
        "lists_generated_at": p.get("generated_at"),
    }


# ── Model-prior classifier (Stage 4 of the four-step lookup) ────────────────


_MODEL_PRIOR_CACHE: dict[str, tuple[SourceTier, str]] = {}
_MODEL_PRIOR_LOCK = threading.Lock()

# Tables-backed persistent cache so a Claude classification for one
# domain doesn't have to repeat on every worker / pod restart. Set up
# lazily on first miss; failures (Tables unreachable, env not set)
# silently fall back to in-memory-only.
_PERSISTENT_TABLE_NAME = "SourceTierCache"
_PERSISTENT_PARTITION = "domains"
_persistent_table_uninit = object()
_persistent_table_lock = threading.Lock()


def _get_persistent_table():
    """Lazy Tables client for SourceTierCache. Returns None when not configured."""
    global _persistent_table_client
    if _persistent_table_client is _persistent_table_uninit:
        # First call: try to initialize.
        with _persistent_table_lock:
            if _persistent_table_client is _persistent_table_uninit:
                _persistent_table_client = _init_persistent_table()
    return _persistent_table_client


def _init_persistent_table():
    import os
    backend = os.getenv("DERAD_SOURCE_CACHE_BACKEND", "tables").lower()
    if backend != "tables":
        return None
    endpoint = os.getenv("DERAD_TABLES_ENDPOINT")
    if not endpoint:
        return None
    try:
        from azure.core.exceptions import ResourceExistsError
        from azure.data.tables import TableServiceClient
        from azure.identity import DefaultAzureCredential
        svc = TableServiceClient(
            endpoint=endpoint,
            credential=DefaultAzureCredential(),
            connection_timeout=10,
            read_timeout=15,
        )
        try:
            svc.create_table(_PERSISTENT_TABLE_NAME)
            logger.info("Created %s table", _PERSISTENT_TABLE_NAME)
        except ResourceExistsError:
            pass
        return svc.get_table_client(_PERSISTENT_TABLE_NAME)
    except Exception:
        logger.warning(
            "SourceTierCache init failed; running with in-memory-only cache.",
            exc_info=True,
        )
        return None


_persistent_table_client = _persistent_table_uninit


def _persistent_get(domain: str) -> Optional[tuple[SourceTier, str]]:
    tbl = _get_persistent_table()
    if tbl is None:
        return None
    try:
        ent = tbl.get_entity(_PERSISTENT_PARTITION, domain)
    except Exception:
        return None
    tier = ent.get("tier")
    rationale = ent.get("rationale") or ""
    if not tier:
        return None
    return tier, rationale


def _persistent_put(domain: str, tier: SourceTier, rationale: str) -> None:
    tbl = _get_persistent_table()
    if tbl is None:
        return
    try:
        tbl.upsert_entity({
            "PartitionKey": _PERSISTENT_PARTITION,
            "RowKey": domain,
            "tier": tier,
            "rationale": rationale,
        })
    except Exception:
        logger.warning("SourceTierCache upsert failed for %r", domain, exc_info=True)


_MODEL_PRIOR_SYSTEM = """You classify web-domain reliability for a fact-checking pipeline. For each input domain, decide ONE tier from this exact set:

- "fact-checker" — IFCN signatory or nationally-recognized fact-checking organisation (Snopes, FactCheck.org, Politifact, AFP Fact Check, AltNews, etc.).
- "reputable-news" — major newspaper/broadcaster/magazine with clear editorial standards and a track record of corrections (AP, Reuters, BBC, NYT, Guardian, Le Monde, Spiegel, etc.).
- "primary-source" — government, IGO, academic institution, peer-reviewed journal, or major institutional publisher (whitehouse.gov, who.int, nature.com, nih.gov, etc.).
- "aggregator" — content aggregator without significant original reporting (news.yahoo.com, news.google.com, etc.).
- "low-quality" — outlet community-consensus marked as unreliable, conspiracy, partisan-propaganda, or known to recycle hoaxes (naturalnews, infowars, gateway pundit, RT, Sputnik, etc.).
- "satirical" — self-described or widely-recognized satirical / fictional news site (The Onion, Babylon Bee, World News Daily Report, etc.).
- "unknown" — you have no confident prior on this domain.

For each domain, give a one-line rationale. Be conservative — if you're not sure, return "unknown".

Output a JSON object: a single top-level field `classifications` mapping each input domain → {tier, rationale}.
"""


def _classify_via_model_batch(domains: list[str]) -> dict[str, tuple[SourceTier, str]]:
    """Classify a batch of unknown domains. Layered cache:
      1. In-memory per-worker dict (fastest).
      2. Persistent Azure Tables row (fleet-wide; survives restarts).
      3. Single Claude call for anything still unknown; results write
         back to both caches.
    """
    if not domains:
        return {}

    # Layer 1 — in-memory cache.
    result: dict[str, tuple[SourceTier, str]] = {}
    fresh: list[str] = []
    with _MODEL_PRIOR_LOCK:
        for d in domains:
            cached = _MODEL_PRIOR_CACHE.get(d)
            if cached is not None:
                result[d] = cached
            else:
                fresh.append(d)
    if not fresh:
        return result

    # Layer 2 — persistent Tables cache. Populate the in-memory cache from
    # any hits so subsequent calls in this worker skip the lookup.
    still_unknown: list[str] = []
    for d in fresh:
        persisted = _persistent_get(d)
        if persisted is not None:
            with _MODEL_PRIOR_LOCK:
                _MODEL_PRIOR_CACHE[d] = persisted
            result[d] = persisted
        else:
            still_unknown.append(d)
    if not still_unknown:
        return result

    # Layer 3 — Claude classifier for the remaining domains.
    from pydantic import BaseModel

    class _Entry(BaseModel):
        tier: SourceTier
        rationale: str = ""

    class _BatchClassification(BaseModel):
        classifications: dict[str, _Entry]

    from .llm import call_claude_json
    user_prompt = json.dumps({"domains": sorted(set(still_unknown))}, indent=2)
    try:
        out = call_claude_json(
            prompt=user_prompt,
            schema=_BatchClassification,
            system=_MODEL_PRIOR_SYSTEM,
            reasoning_effort="low",
            max_tokens=2048,
            timeout=30.0,
        )
    except (ValueError, TimeoutError, anthropic.APIConnectionError):
        # anthropic.APITimeoutError does NOT subclass TimeoutError — it
        # subclasses APIConnectionError — so it must be caught explicitly
        # here to degrade gracefully instead of propagating.
        logger.warning(
            "Model-prior classification failed; %d domains stay unknown.",
            len(still_unknown), exc_info=True,
        )
        return result

    with _MODEL_PRIOR_LOCK:
        for d, entry in out.classifications.items():
            tier = entry.tier
            rationale = entry.rationale or "Model parametric prior."
            _MODEL_PRIOR_CACHE[d] = (tier, rationale)
            result[d] = (tier, rationale)
            _persistent_put(d, tier, rationale)
    return result


# ── Public API ──────────────────────────────────────────────────────────────


def _normalize_domain(url: str) -> str:
    try:
        host = urlparse(url).hostname or ""
    except ValueError:
        return ""
    return host.lower()


def _registered_domain(host: str) -> str:
    """Strip www. and other common subdomain prefixes."""
    if not host:
        return ""
    if host.startswith("www."):
        return host[4:]
    return host


def _host_in_set(host: str, domains: set[str]) -> bool:
    """True if host, or any parent of it, is in `domains` (subdomain fallback)."""
    if host in domains:
        return True
    parts = host.split(".")
    for i in range(1, len(parts) - 1):
        if ".".join(parts[i:]) in domains:
            return True
    return False


def is_non_evidence_domain(url: str) -> bool:
    """True if `url` is a non-evidentiary domain (stock-image marketplace,
    shopping site, UGC content farm) that should be dropped before it ever
    enters the evidence table. Subdomain → parent matching applies."""
    host = _registered_domain(_normalize_domain(canonicalize_url(url)))
    return bool(host) and _host_in_set(host, _NON_EVIDENCE_DOMAINS)


def _lookup_curated(host: str) -> tuple[SourceTier, TierSource, str] | None:
    """Check curated tables with subdomain → parent fallback."""
    if host in _TIER_BY_DOMAIN:
        return _TIER_BY_DOMAIN[host]
    # Strip subdomains one segment at a time and re-check.
    parts = host.split(".")
    for i in range(1, len(parts) - 1):
        parent = ".".join(parts[i:])
        if parent in _TIER_BY_DOMAIN:
            return _TIER_BY_DOMAIN[parent]
    return None


def classify_url(url: str) -> SourceQualityEntry:
    """Classify a single URL. Equivalent to build_quality_table([url])[0] but
    skips the batch optimization — prefer the batch entrypoint for multiple URLs."""
    canonical = canonicalize_url(url)
    host = _registered_domain(_normalize_domain(canonical))
    if not host:
        return SourceQualityEntry(
            url=canonical, tier="unknown", tier_source="model-prior",
            rationale="URL has no parseable host.",
        )
    hit = _lookup_curated(host)
    if hit:
        tier, tier_source, rationale = hit
        return SourceQualityEntry(url=canonical, tier=tier, tier_source=tier_source, rationale=rationale)
    classified = _classify_via_model_batch([host])
    if host in classified:
        tier, rationale = classified[host]
        return SourceQualityEntry(
            url=canonical, tier=tier, tier_source="model-prior", rationale=rationale,
        )
    return SourceQualityEntry(
        url=canonical, tier="unknown", tier_source="model-prior",
        rationale=f"No entry for {host!r}; model fallback also returned unknown.",
    )


def build_quality_table(urls: list[str]) -> list[SourceQualityEntry]:
    """Build the source_quality_table for a set of URLs, de-duplicated in
    input order. Non-evidentiary domains (stock-image / shopping / UGC-farm)
    are dropped entirely; unknown domains are batched into a single Claude call."""
    seen: set[str] = set()
    ordered_urls: list[str] = []
    dropped = 0
    for url in urls:
        canonical = canonicalize_url(url)
        if canonical in seen:
            continue
        seen.add(canonical)
        if is_non_evidence_domain(canonical):
            dropped += 1
            continue
        ordered_urls.append(canonical)
    if dropped:
        logger.info("source classifier: dropped %d non-evidence URL(s)", dropped)

    # First pass — curated lookup. Collect unknowns for batched model call.
    cached: dict[str, SourceQualityEntry] = {}
    unknown_hosts: list[str] = []
    host_by_url: dict[str, str] = {}
    for url in ordered_urls:
        host = _registered_domain(_normalize_domain(url))
        host_by_url[url] = host
        if not host:
            cached[url] = SourceQualityEntry(
                url=url, tier="unknown", tier_source="model-prior",
                rationale="URL has no parseable host.",
            )
            continue
        hit = _lookup_curated(host)
        if hit:
            tier, tier_source, rationale = hit
            cached[url] = SourceQualityEntry(
                url=url, tier=tier, tier_source=tier_source, rationale=rationale,
            )
        elif host not in unknown_hosts:
            unknown_hosts.append(host)

    # Second pass — single batched model call for unknowns.
    model_results: dict[str, tuple[SourceTier, str]] = {}
    if unknown_hosts:
        logger.info("source classifier: %d unknown host(s) → batch model call", len(unknown_hosts))
        model_results = _classify_via_model_batch(unknown_hosts)

    out: list[SourceQualityEntry] = []
    for url in ordered_urls:
        if url in cached:
            out.append(cached[url])
            continue
        host = host_by_url[url]
        if host in model_results:
            tier, rationale = model_results[host]
            out.append(SourceQualityEntry(
                url=url, tier=tier, tier_source="model-prior", rationale=rationale,
            ))
        else:
            out.append(SourceQualityEntry(
                url=url, tier="unknown", tier_source="model-prior",
                rationale=f"No entry for {host!r}; model fallback returned no classification.",
            ))
    return out
